### PR TITLE
Drag release num

### PR DESCRIPTION
**Pull request by PeterMitrano**
#### What issue does this fix?
- Release numbers work
#### What features does this propose?
- Drag and drop and delete release numbers
#### Did you add tests to cover the code you propose?

fuck testing

### CODE REVIEW

**Comment by jkuszmaul** [comment]
Does this actually reduce coverage by 7%? If so, fix that. Also, merge conflicts.

**Comment by jpmartin2** [comment]
Also, dragging release numbers from the board doesn't add the snapshot image (or I don't see it show up).

It would be nice if you could add a test or two since you added a sizable amount of code.

**Comment by jpmartin2** [comment]
You can also drag around release numbers while playing a level

**Comment by jkuszmaul** [comment]
You can check `Board.isEditor` in the move class to fix the dragging (for when you return whether the move is valid).

**Comment by garrisonhefter** [comment]
After an attempted drag to bullpen, the number will clone itself.

**Pull request merged**
