### PR TITLE
Various drag & drop features

### PR DESCRIPTION
**Pull request by PeterMitrano**
#### What issue does this fix?
- Issue #27 , except no painting on the board. Waiting for #57 
#### What features does this propose?
- Implement drop on BoardView and Bullpen
- Remove piece when drag is initiated
- Add piece to Bullpen if dropped (doesn't check where it came from)
- Fails when dropped anywhere else (including outside application)
- Doesn't display pieces dropped on the board
- Added some `toString()` methods
- removed more useless controllers
#### Did you add tests to cover the code you propose?
- Test adding pieces to the bullpen

### CODE REVIEW

**Comment by LoganTutt** [comment]
The scaling for the dragged pieces is wrong on my computer, the pieces are significantly too small.

**Comment by jpmartin2** [comment]
Dragging a piece onto the board causes the piece to disappear from the bullpen, but then adding a new piece to the bullpen causes the first piece to reappear in the bullpen.

**Comment by PeterMitrano** [comment]
That's beacuse the model isn't updated when a piece is removed. Only the
view is removed. I haven't decided if we should do it that way, and then
remove on successful drop, or remove it immediately and worry about adding
it back.

**Comment by PeterMitrano** [comment]
screenshot plz @LoganTutt

**Comment by PeterMitrano** [comment]
I know this doesn't address all drag & drop issues but I don't want to tack anything else more on. Can we get this merged?

**Comment by jkuszmaul** [comment]
I'm fine with merging it, but do we have a (written down) list of the main things that this doesn't deal with (that you might normally expect it to)?

**Comment by PeterMitrano** [comment]
I updated the description to be more complete

**Pull request merged**
