### PR TITLE
Improved Play View (not ready)

### PR DESCRIPTION
**Pull request by PeterMitrano**
#### What issue does this fix?
- Player had default info and no way to set it programatically
#### What features does this propose?
- Added LevelWidget's to the player
#### Did you add tests to cover the code you propose?

We already have good coverage and I only added 45 lines.

### CODE REVIEW

**Comment by jpmartin2** [comment]
I don't think this really makes sense, at least with the current state of the LevelViewWidgets, since they have the controls to change the settings.

**Comment by PeterMitrano** [comment]
I propose having an editorPanel and a playerPanel for each level widget.

**Comment by PeterMitrano** [comment]
We can merge #77  first and replace that solution with this one if we have time.

**Comment by jpmartin2** [comment]
That seems fine to me, though I'd recommend passing the level model through and then have the LevelView get the corresponding view.

**Pull request closed without merging**
