### PR TITLE
Release widget

### PR DESCRIPTION
**Pull request by PeterMitrano**
#### What features does this propose?
- Added release widget in builder
### Known bugs
- Winning custom with colors doesn't work
- No way to remove them
- No way to move them around the board
- It's ugly
- 
#### Did you add tests to cover the code you propose?

nahhh. Gonna merge this with master, just gimme a minute

### CODE REVIEW

**Comment by PeterMitrano** [comment]
@jkuszmaul @LoganTutt @LordPython Ready to go. Plz test away

**Comment by PeterMitrano** [comment]
Changing board size causes NullPointerException

**Comment by jpmartin2** [comment]
The spinner seems to only go down.

**Comment by PeterMitrano** [comment]
changing level type doesn't remove numbers

**Comment by PeterMitrano** [comment]
@LordPython No it goes up fine for me. Should be from 1 to 6

**Comment by jpmartin2** [comment]
Pressing on the up arrow for me causes the number to count down instead of up.

**Comment by jpmartin2** [comment]
Except now it works. Weird

**Comment by PeterMitrano** [comment]
You're right weird shit is happening

**Comment by jpmartin2** [comment]
Ah. Clicking on the lower half of the up button goes down. The upper half goes up.

**Comment by jpmartin2** [comment]
Also I can't set the number of moves for a release level properly right now (doesn't seem to be saving properly)

**Comment by jpmartin2** [comment]
Also, switching level types should clear the numbers off the board. I think this might be just a matter of refreshing the board.

**Comment by jpmartin2** [comment]
Some drag and drop stuff occasionally breaks now as well, throwing null pointer exceptions on 126 of BoardView.java and 55 of BullpenView.java

Seems to be mostly after changing level type

**Comment by PeterMitrano** [comment]
@LordPython  I can't figure out where I need to clear the numbers

**Comment by jpmartin2** [comment]
It's just that the board isn't getting redrawn after changing level types.

Hmmmm... Maybe not. I can drag pieces onto the board and the release numbers are still there.

**Pull request merged**
