### PR TITLE
Use testfx

### PR DESCRIPTION
**Pull request by jkuszmaul**
#### What issue does this fix?
#34
#### What features does this propose?

Add testing for GUI features.

I'm not sure how to make eclipse recognize the TestFX libraries.

I guess I shouldn't base this on #48, but I wanted to test some of the features that I added.

### CODE REVIEW

**Comment by PeterMitrano** [comment]
Well it seems obvious to me why this is failing... it attempts to open the gui
That's not gonna work on travis.
I'm not sure how it's supposed to work on a server

**Comment by jkuszmaul** [comment]
Yeah, I wasn't sure whether that would work on the travis server, but I wasn't sure (a) why it didn't just straight up fail, and (b) you never know; it could work.

**Comment by PeterMitrano** [comment]
I'm deeming this out of scope, although it is cool and does work.

**Comment by PeterMitrano** [comment]
As james pointed out in #34, we really need something like this in order for test coverage to work.

**Comment by PeterMitrano** [comment]
@jkuszmaul branched this off #44, but since we're probably not accepting that I'm going to make a different one the demonstrates gui tests without needing those changes.

**Pull request closed without merging**
